<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LTB0216412" ignored="0" name="Validating first Searched Link Text via search engine" tests="2" failures="1" timestamp="2022-02-03T23:53:38 IST" time="94.15" errors="0">
  <testcase name="validate_first_link" time="79.231" classname="test.validateSearchPageContentTest">
    <failure type="java.lang.AssertionError" message="expected [Welcome to Python.org] but found [Learn Python Today - Start Learning Today]">
      <![CDATA[java.lang.AssertionError: expected [Welcome to Python.org] but found [Learn Python Today - Start Learning Today]
at test.validateSearchPageContentTest.validate_first_link(validateSearchPageContentTest.java:75)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validate_first_link -->
  <testcase name="validate_first_link" time="5.435" classname="test.validateSearchPageContentTest"/>
</testsuite> <!-- Validating first Searched Link Text via search engine -->
